### ISSUE TITLE
The Windows binary requires MSVCR100D.DLL

### ISSUE THREAD

**Issue by lynnntropy** [robertdavidgraham/heartleech#10]
This is an issue caused by the binary being compiled as a `debug` binary, not `release`. Had it been compiled as a release binary, it would require MSVCR100.DLL (note the absence of the D), which is the intended behavior and is contained in the VC++ 2010 redistributable.

This is fixable by simply packaging the DLL with the binary (which is how I made it work, since I only have VS2013, and the DLL comes with VS2010), or by recompiling the binary in `release` mode.

**Comment by robertdavidgraham** [comment]
I've changed it to Release
