### ISSUE TITLE
Example outliers that cause the app to hang

### ISSUE THREAD

**Issue by AnonymousScanner** [robertdavidgraham/heartleech#16]
Here's a few examples of outliers that cause the binary to hang or otherwise act weird/broken:

forbes.com
39.net
github.io
nydailynews.com
therichest.com
canalplus.fr
abola.pt
local.com

I used `./heartleech <insert_domain> -a` to test them.

**Comment by robertdavidgraham** [comment]
I think all the problems are fixed. It would hang for various reasons, but I think they all work now.
