### ISSUE TITLE
inet_ntop on Windows XP

### ISSUE THREAD

**Issue by postacik** [robertdavidgraham/heartleech#20]
inet_ntop function does not exist on Windows XP. I patched your code as the following. (sorry for the formatting, I don't know how to format code in this editor)

const char\* inet_ntop2(int af, const void\* src, char\* dst, int cnt)
{

```
struct sockaddr_in srcaddr;

memset(&srcaddr, 0, sizeof(struct sockaddr_in));
memcpy(&(srcaddr.sin_addr), src, sizeof(srcaddr.sin_addr));

srcaddr.sin_family = af;
if (WSAAddressToString((struct sockaddr*) &srcaddr, sizeof(struct sockaddr_in), 0, dst, (LPDWORD) &cnt) != 0) {
    DWORD rv = WSAGetLastError();
    printf("WSAAddressToString() : %d\n",rv);
    return NULL;
}
return dst;
```

}

static const char *my_inet_ntop(int family, struct sockaddr *sa, char *dst, size_t sizeof_dst)
{
    switch (family) {
    case AF_INET:
        inet_ntop2(AF_INET, &(((struct sockaddr_in *)sa)->sin_addr),
                dst, sizeof_dst);
        break;
    case AF_INET6:
        inet_ntop2(AF_INET6, &(((struct sockaddr_in6 *)sa)->sin6_addr),
                dst, sizeof_dst);
        break;
    default:
        dst[0] = '\0';
    }

```
return dst;
```

}

**Comment by robertdavidgraham** [comment]
I fixed inet_top, but there may be other WinXP bugs. I need to spend more work on it.
