### ISSUE TITLE
pthread_create build failure

### ISSUE THREAD

**Issue by digininja** [robertdavidgraham/heartleech#26]
This is on a different Debian 64bit machine. OpenSSL freshly pulled from Github.

$ gcc ../heartleech/heartleech.c libssl.a libcrypto.a -ldl -lpthread -o heartleech -I./include
../heartleech/heartleech.c: In function ‘main’:
../heartleech/heartleech.c:3182:21: warning: passing argument 3 of ‘pthread_create’ from incompatible pointer type [enabled by default]
                     pthread_create(&handle, 0, (void(_)(void_))run_scan, &args);
                     ^
In file included from ../heartleech/heartleech.c:77:0:
/usr/include/pthread.h:244:12: note: expected ‘void \* (_)(void *)’ but argument is of type ‘void (_)(void *)’
 extern int pthread_create (pthread_t *__restrict __newthread,

**Comment by robertdavidgraham** [comment]
That should should be a warning not a failure, but I'll go fix it.

**Comment by digininja** [comment]
Ye, my mistake, I looked in the heartleech directory for the binary but it is built into the openssl directory instead as that is what I asked for when compiling. Just updated and the warnings are gone and the binary is built as it probably was before.

**Comment by robertdavidgraham** [comment]
I, too, am confused by this. It's really annoying, but I know no better solution to the problem :)
